ALTER TABLE Member
ADD COLUMN github_id VARCHAR(255) UNIQUE;

CREATE TABLE ApiKey (
    key_id SERIAL PRIMARY KEY,
    member_id INT UNIQUE REFERENCES Member(member_id) ON DELETE CASCADE,
    key_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (key_hash)
);

CREATE TRIGGER set_updated_at
BEFORE UPDATE ON ApiKey
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();