name: Generate DeepWiki Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: DeepWiki Documentation Generator
        uses: he1senbrg/deepwiki-action@v1.1
        with:
          branch: 'develop'
          message: 'Updated documentation from DeepWiki'
